#!/usr/bin/env python

import sys
import json
import os
import tqdm
import requests

if len(sys.argv) != 2:
        print("Usage: ./getProgram data_file")
        exit(1)

filename = sys.argv[1]

op_filename = filename + "_prgfiles.json"
programs = []

with open(filename, 'r') as json_file_collection:
        os.system('rm -rf ' + op_filename)
        for json_str in tqdm.tqdm(json_file_collection.readlines()):
                obj = json.loads(json_str)
                code = obj['left_context'].replace('"', '\"', -1) + '??' + obj['right_context'].replace('"', '\"', -1)
                programs.append({
                        "filepath": obj['filepath'],
                        "target_seq": obj['target_seq'],
                        "line": obj['line'],
                        "code":        code
                })

with open(op_filename, 'w') as op_file:
        print("Saving programs to " + op_filename)
        json.dump(programs, op_file, indent=4)
