#!/bin/bash
#PBS -N mcts
#PBS -q debug
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=2
#PBS -k oe
#PBS -m ae

# Note that any line starting with "#PBS" will be treated as a task configuration

# qsub will start a new process to execute the following commands

rm -rf ${bench}/edb_dumps
mkdir -p ${bench}/edb_dumps
rm -rf ${bench}/results
mkdir -p ${bench}/results
mkdir -p ${bench}/cluster_logs
rm -rf ${bench}/cluster_logs/dumplog.*
./extract_all.sh python-edb-queries/edb-queries ${bench}/codeqldb ${bench}/edb_dumps 8 > ${bench}/cluster_logs/dumplog.out 2>${bench}/cluster_logs/dumplog.err
