#!/usr/bin/env bash
start=0
end=50
width=50
n=0
filelist="$1"
for i in $(cat $filelist)
do
    if (($n >= $start && $n < $end))
    then
        # fname=$(basename $i)
        dname="../datasets/cubert/$i"
        echo "Running for $dname"
        ./cluster_script.sh "$dname" &
        echo "$n added till now"
    else
        echo "Waiting for all background processes to finish"
        wait
        echo "Background processes finished"
        start=$end
        end=$((end+width))
        echo "Setting start and end to $start and $end"
    fi
    n=$((n+1))
done
